### ISSUE TITLE
Question about the (private) function Error.get_id/1

### ISSUE THREAD

**Issue by florinpatrascu** [mschae/boltex#14]
Hi @mschae - I am using a newer version of an ssl driver and it has a different "port" info, that breaks the `Error.get_id/1`. While I could send a PR describing the new parameter (`{:sock_ref, socket, supervisor, receiver, sender}` fwiw) I am not sure this is the best way to go, as we'll always have troubles every time we'll try a new ssl implementation. Right now, I am catching the `ArgumentError` exception, correctly triggered in this module (by the `Port.info/2`), and continue. But this is just a patch, which I'd rather avoid, if possible. Would you have an idea about how to relax this function, or maybe even if it has any future role, in Boltex? Thank you - Florin

**Comment by mschae** [comment]
Hey @florinpatrascu,

that's a good point. While I would like us to add implementations like the one above to `get_id` to help with debugging, we should definitely make it resilient for transports we haven't yet looked into.

I took the liberty of just throwing that into #15 with other fixes.

I'd appreciate if you could test that branch and let me know if it properly addresses the problem (and if everything still works). Once that looks good I'll release a new version.

As mentioned above, feel free to add a PR to address resolving the port id for the newer version of the driver.

Thanks,
Michael

**Comment by florinpatrascu** [comment]
Hey @mschae - this version is a winner :) Please release it, when your time allows. Thank you! - Florin

**Comment by florinpatrascu** [comment]
🍻

**Comment by mschae** [comment]
Released v0.2.1. Thanks for helping me improve boltex!
